[package]
name = "warp-runner"
version = "0.3.0"
authors = ["Diego Giagio <diego@giagio.com>"]
edition = "2024"

[dependencies]
memmem = "0.1.1"
flate2 = "1.1.1"
tar = "0.4.44"
dirs = "1.0.5"
log = "0.4.27"
simple_logger = "1.16.0"
