[package]
name = "warp-packer"
version = "0.3.0"
authors = ["Diego Giagio <diego@giagio.com>"]
edition = "2024"

[dependencies]
clap = "2.34.0"
dirs = "1.0.5"
reqwest = "0.9.24"
tempdir = "0.3.7"
flate2 = "1.1.1"
tar = "0.4.44"
sha2 = "0.10.8"
lazy_static = "1.5.0"
