name: Cross Build and Release

on:
  workflow_dispatch:

jobs:
  cross-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust and targets
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu, x86_64-apple-darwin

      - name: Install Cross Compilation Tools
        run: |
          # Windows 工具链
          sudo apt-get update
          sudo apt-get install -y g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64
          
          # macOS 工具链 (使用 zig)
          wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
          tar -xf zig-linux-x86_64-0.11.0.tar.xz
          echo "$(pwd)/zig-linux-x86_64-0.11.0" >> $GITHUB_PATH
          
          # Linux 工具链
          sudo apt-get install -y binutils

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild

      - name: Build Targets
        run: |
          cargo build --release -p warp-runner --target x86_64-pc-windows-gnu
          x86_64-w64-mingw32-strip target/x86_64-pc-windows-gnu/release/warp-runner.exe
          
          cargo build --release -p warp-runner --target x86_64-unknown-linux-gnu
          strip target/x86_64-unknown-linux-gnu/release/warp-runner
          
          cargo zigbuild --release -p warp-runner --target x86_64-apple-darwin
          zig strip target/x86_64-apple-darwin/release/warp-runner
          
          cargo build --release -p warp-packer --target x86_64-pc-windows-gnu
          x86_64-w64-mingw32-strip target/x86_64-pc-windows-gnu/release/warp-packer.exe
          
          cargo build --release -p warp-packer --target x86_64-unknown-linux-gnu
          strip target/x86_64-unknown-linux-gnu/release/warp-packer
          
          cargo zigbuild --release -p warp-packer --target x86_64-apple-darwin
          zig strip target/x86_64-apple-darwin/release/warp-packer
        env:
          CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER: x86_64-w64-mingw32-gcc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: multi-platform-binaries
          path: |
            target/x86_64-pc-windows-gnu/release/warp-packer.exe
            target/x86_64-unknown-linux-gnu/release/warp-packer
            target/x86_64-apple-darwin/release/warp-packer