name: Cross Build and Release

on:
  workflow_dispatch:

jobs:
  cross-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust and targets
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu

      - name: Install Cross Compilation Tools
        run: |
          # Windows 目标：安装 mingw-w64 工具链
          sudo apt-get update
          sudo apt-get install -y g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64
          
          # Linux 目标：确保 strip 工具可用
          sudo apt-get install -y binutils

      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild

      - name: Build Targets
        run: |
          cargo build -p warp-runner --release --target x86_64-unknown-linux-gnu
          strip target/x86_64-unknown-linux-gnu/release/warp-runner
          
          cargo build -p warp-runner --release --target x86_64-pc-windows-gnu
          strip target/x86_64-pc-windows-gnu/release/warp-runner.exe
          
          cargo build -p warp-packer --release --target x86_64-unknown-linux-gnu
          strip target/x86_64-unknown-linux-gnu/release/warp-packer
          
          cargo build -p warp-packer --release --target x86_64-pc-windows-gnu
          strip target/x86_64-pc-windows-gnu/release/warp-packer.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: multi-platform-binaries
          path: |
            target/x86_64-pc-windows-gnu/release/warp-packer.exe
            target/x86_64-unknown-linux-gnu/release/warp-packer